debug=true
spring.application.name=S05T01

# MongoDB
# --- CONEXIÓN EXTERNA MONGODB ATLAS ---
spring.data.mongodb.uri=mongodb+srv://urian_db_user:eCBsvuM2ttR95cRX@TU_CLUSTER_URL/blackjack_db?retryWrites=true&w=majority

# --- 2. SQL AIVEN (Ranking) ---
spring.r2dbc.url=r2dbc:mysql://mysql-20fff2a-urianr-08a0.d.aivencloud.com:13255/defaultdb?sslMode=REQUIRED
spring.r2dbc.username=avnadmin
spring.r2dbc.password=${AIVEN_PASSWORD}

# --- 3. INICIALIZACIÓN ---
# Esto intentará ejecutar tu archivo schema.sql en Aiven al arrancar
spring.sql.init.mode=always

