spring.application.name=S05T01
debug=false


spring.data.mongodb.uri=mongodb+srv://urian_db_user:eCBsvuM2ttR95cRX@urian1983mongodbserver.q1t4g5p.mongodb.net/blackjack_db?retryWrites=true&w=majority&appName=Urian1983MongoDBServer

spring.r2dbc.url=r2dbc:mysql://mysql-20fff2a-urianr-08a0.d.aivencloud.com:13255/defaultdb?sslMode=REQUIRED
spring.r2dbc.username=avnadmin
spring.r2dbc.password=AVNS_3hfEVREbiMAYLBJ9YTf

spring.sql.init.mode=always

